---
kind: pipeline
name: default

steps:
- name: test
  image: rust:1.35
  commands:
  - cargo build --verbose --all
  - cargo test --verbose --all
---
kind: signature
hmac: 903d5389393e26c7603049a02649040e60e6485fcbaa539966a94c2eb19e267d

...
