on: [push]

name: Build

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.44.0"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
